import { Header } from '@ems/common-ui';

export const metadata = {
  title: 'Employees',
  description: 'Generated by create-nx-workspace',
};

export default function EmployeeLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="container mx-auto">
      <Header>Employees</Header>
      {children}
    </div>
  );
}
